name: flutter_material_pickers
description: A flutter package for easily and consistently showing material themed picker dialogs.
version: 3.1.0
homepage: https://github.com/codegrue/flutter_material_pickers
issue_tracker: https://github.com/codegrue/flutter_material_pickers/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.6.0
  intl: ^0.17.0
  file_picker: ^3.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
